alg_name: 'DINM'
model_name: "./hugging_cache/Mistral-7B-v0.1"  # the vanilla LLM path  
model_class: AutoModelForCausalLM
tokenizer_class: AutoTokenizer
device: 2



suffix_system_prompt: "If the user's request is reasonable, give the correct answer. Please give the right response:"

# You can specify the edited layer for all data in advance, for example: layer: [31]
# if you set layers : [], DINM will locates the toxic layer for each instance in safety_editor.py
layers: []
num_steps: 10
batch_size: 1

# max_length is the maximum length of this LLM (Mistral-7B-v0.1).
max_length: 2048

# if you use SafeEdit dataset for evaluation, it is recommended to set max_output_length to 600 for the response by LLM. 
# For some role-playing attack prompts, LLMs may initially generate safe responses and then suddenly generate toxic text. Therefore, you should set enough max_output_length (600) to evaluate the safety of LLM.
max_output_length: 600


lr: 1e-5
weight_decay: 0
kl_factor: 0.1
norm_constraint: false
rewrite_module_tmp: 'model.layers.{}.mlp.down_proj.weight'
layer_module_tmp: 'model.layers.{}'
mlp_module_tmp: 'model.layers.{}.mlp'
attn_module_tmp: 'model.layers.{}.self_attn'
ln_f_module: 'model.norm'
lm_head_module: 'lm_head'
model_parallel: false
