relationid_words={
'P36': ['has capital'],
'P26': ['the spouse of'],
'P38': ['the currency'],
'P169': ['chief executive officer'],
'P35': ['head of state or government'],
'P634': ['team captain'],
'P185': ['doctoral student'],
'P1429': ['has pet'],
'P355': ['has subsidiary'],
'P112': ['founded by'],
'P39': ['holds the position'],
'P277': ['the programming language written'],
'P2389': ['is directed from'],
'P86': ['the composer of'],
'P162': ['produced by'],
'P108': ['is employed by'],
'P119': ['The burial place of'],
'P110': ['the illustrator'],
'P749': ['parent organization'],
'P287': ['designed by'],
'P37': ['official language is'],
'P103': ['native language'],
'P176': ['manufactured by'],
'P1589': ['the lowest point of'],
'P50': ['has author'],
'P47': ['shares border with'],
'P1327': ['partner in business or sport'],
'P530': ['diplomatic relation'],
'P190': ['twinned administrative body'],
're_P112': ['has founded'],
're_P39': ['is held by'],
're_P277': ['is the programming language of'],
're_P2389': ['is the head of'],
're_P86': ['is the composer of'],
're_P162': ['has produced'],
're_P108': ['has employed'],
're_P119': ['is the burial place of'],
're_P110': ['was illustrated by'],
're_P749': ['is the parent organization'],
're_P287': ['has designed'],
're_P37': ['is the official language of'],
're_P103': ['is the native language of'],
're_P176': ['has manufactured'],
're_P1589': ['is the lowest point of'],
're_P50': ['has written the'],
}