alg_name: "KN"
#model_name: "./hugging_cache/llama-2-7b"
#model_name: "./hugging_cache/Llama-3-8B"
model_name: "./hugging_cache/Llama-2-13b-chat-hf"
device: 0
model_parallel: false

lr_scale: 1.0
n_toks: 10
refine: false
batch_size: 1
steps: 1
adaptive_threshold: 0.2
p: 0.4